### ISSUE TITLE
M1 Macmini无法安装  OS: macOS 12.5.1 21G83 arm64 

### ISSUE THREAD

**Issue by finch-ift** [happynclient/happynmacos#1] opened 2022-08-18 06:04 UTC
❯ brew install tuntap --cask
==> Caveats
tuntap requires a kernel extension to work.
If the installation fails, retry after you enable it in:
  System Preferences → Security & Privacy → General

For more information, refer to vendor documentation or this Apple Technical Note:
  https://developer.apple.com/library/content/technotes/tn2459/_index.html

==> Downloading https://download.happyn.vip/macos/happynet-tuntap.tar.gz
Already downloaded: /Users/***/Library/Caches/Homebrew/downloads/6251e9c87afd911ee9166b0bb27a160038270f3ea0d25c6ad157218e67a3686b--happynet-tuntap.tar.gz
==> Installing Cask tuntap
==> Running installer for tuntap; your password may be necessary.
Package installers may write to any location; options such as `--appdir` are ignored.
Password:
installer: Package name is TunTap Installer package
installer: Installing at base path /
installer: The install failed. (安装器遇到了一个错误，导致安装失败。请联系软件生产企业以获得帮助。 运行软件包“tuntap_20150118.pkg”的脚本时出错。)
==> Purging files for version 20150118 of Cask tuntap
Error: Failure while executing; `/usr/bin/sudo -E -- /usr/bin/env LOGNAME=*** USER=*** USERNAME=*** /usr/sbin/installer -pkg /opt/homebrew/Caskroom/tuntap/20150118/tuntap_20150118.pkg -target /` exited with 1. Here's the output:
installer: Package name is TunTap Installer package
installer: Installing at base path /
installer: The install failed. (安装器遇到了一个错误，导致安装失败。请联系软件生产企业以获得帮助。 运行软件包“tuntap_20150118.pkg”的脚本时出错。)

**Comment by happyntec** [comment] 2022-11-11 07:04
M1还没有支持，正在开发中；近期会发布

**Comment by happyntec** [comment] 2022-11-11 07:16
Duplicate of #2

**Closed as completed** 2022-11-11 07:16 UTC
Labels: duplicate, enhancement, good first issue
